project:
  type: website

website:
  title: "Stefan Stojkovic"
  navbar:
    background: primary
    search: true
    right:
      - text: "Home"
        href: index.qmd
      - text: "CV"
        href: cv.qmd
      - text: "Projects"
        href: projects.qmd
      - text: "Education"
        href: education.qmd
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/stojkovicstefan/
      - icon: github
        href: https://github.com/StojkovicS
    #    menu:
     #     - text: Source Code
      #      href:  https://code.com # ovo je za submenu
    permissions:
        pages: write      # Allows deployment to GitHub Pages
        id-token: write   # Enables OIDC authentication
        actions: read     # Grants read access to actions, required for v4

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
